
@idempotencyKey = {{$guid}}


###
POST https://dummybankingapis.onrender.com/api/login
content-type: application/json

{
  "email": "akandesefunmi@gmail.com",
  "password": "mypass23"
}


###
POST https://dummybankingapis.onrender.com/api/register
content-type: application/json

{
  "fullName": "Adeshina oluwasefunmi",
  "email": "akandesefunmi@gmail.com",
  "password": "mypass23"
}
1502308833
1124859232

###
POST https://dummybankingapis.onrender.com/api/auth/transfer
idempotency-Key: {{ idempotencyKey }}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQsImVtYWlsIjoiYWthbmRlc2VmdW5taUBnbWFpbC5jb20iLCJpYXQiOjE3NjM0NTYyODMsImV4cCI6MTc2MzQ1OTg4M30.4gUTekhrKcOskYhLa8_huR7zs2SBPFKNBjzg2kUjpZM

{
  "receiverAccountId": "1502308833",
  "amount": 100.50
}

###
GET https://dummybankingapis.onrender.com/api/auth/details
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQsImVtYWlsIjoiYWthbmRlc2VmdW5taUBnbWFpbC5jb20iLCJpYXQiOjE3NjM1NjM4OTMsImV4cCI6MTc2MzU2NzQ5M30.TNpNyg7rigivOXG6Q5I4Swtz9jo8bSsKvDHx1_L1MSo
Content-Type: application/json
